services:
  # Laravel App
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: protogen-api
    working_dir: /var/www
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/var/www
    depends_on:
      - postgres
    networks:
      - app-network

  # Nginx for Laravel API
  webserver:
    image: nginx:alpine
    container_name: protogen-webserver
    ports:
      - "3333:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./api:/var/www
    depends_on:
      - api
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.protogen.local`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"

  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: protogen-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-protogen_dev}
      POSTGRES_USER: ${POSTGRES_USER:-protogen}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_dev_password_here}
    ports:
      - "3311:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  # React frontend dev server - User Portal
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: protogen-portal
    working_dir: /app
    volumes:
      - ./portal:/app
      - ./shared:/shared
      - ./config:/config
      - /app/node_modules
    ports:
      - "3388:3000"
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=Host(`portal.protogen.local`)"
      - "traefik.http.services.portal.loadbalancer.server.port=3000"

  # React admin dev server - Admin Portal
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: protogen-admin
    working_dir: /app
    volumes:
      - ./admin:/app
      - ./shared:/shared
      - ./config:/config
      - /app/node_modules
    ports:
      - "3355:3001"
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.protogen.local`)"
      - "traefik.http.services.admin.loadbalancer.server.port=3001"

  # pgAdmin - PostgreSQL GUI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: protogen-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@protogen.dev
      PGADMIN_DEFAULT_PASSWORD: ProtogenDevPassword123
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "3322:80"
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.protogen.local`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

volumes:
  postgresdata:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
